module.exports = {
  'short-1': 'var(--md-sys-motion-duration-short-1)',
  'short-2': 'var(--md-sys-motion-duration-short-2)',
  'short-3': 'var(--md-sys-motion-duration-short-3)',
  'short-4': 'var(--md-sys-motion-duration-short-4)',
  'meduim-1': 'var(--md-sys-motion-duration-medium-1)',
  'meduim-2': 'var(--md-sys-motion-duration-medium-2)',
  'meduim-3': 'var(--md-sys-motion-duration-medium-3)',
  'meduim-4': 'var(--md-sys-motion-duration-medium-4)',
  'long-1': 'var(--md-sys-motion-duration-long-1)',
  'long-2': 'var(--md-sys-motion-duration-long-2)',
  'long-3': 'var(--md-sys-motion-duration-long-3)',
  'long-4': 'var(--md-sys-motion-duration-long-4)',
  'extra-long-1': 'var(--md-sys-motion-duration-extra-long-1)',
  'extra-long-2': 'var(--md-sys-motion-duration-extra-long-2)',
  'extra-long-3': 'var(--md-sys-motion-duration-extra-long-3)',
  'extra-long-4': 'var(--md-sys-motion-duration-extra-long-4)',
};