name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 6.7.0
        
    - run: pnpm ci
    - run: pnpm run build
