name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install @wtprograms/material-design
      working-directory: ./material-design
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build @wtprograms/material-design
      working-directory: ./material-design
      run: npm run build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
