name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 6.7.0
        
    - run: pnpm install
    - run: pnpm run build
    
    - id: get_version
      name: Get Version
      uses: jannemattila/get-version-from-tag@v3
    
    - name: Set package.json version
      uses: HarmvZ/set-package-json-version-action@v0.2.5
      with:
        version: ${{ steps.get_version.outputs.version }}

    - name: Publish
      if: success()
      run: pnpm publish --access public
      working-directory: ./dist/wtprograms/material-design
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
